version: "3.8"

services:
  mysql:
    image: mysql
    container_name: project_db
    volumes:
      - ./project_db:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  django:
    container_name: project_backend
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./django/dockerfile

    stdin_open: true
    tty: true
